# Generated by Django 2.2.5 on 2019-10-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20191019_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
