# Generated by Django 2.2.5 on 2019-10-19 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_auto_20191019_0338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLocation',
            new_name='UserInfo',
        ),
    ]
