# Generated by Django 2.2.5 on 2019-10-19 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_auto_20191019_0352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserDetail',
        ),
    ]
