# Generated by Django 2.2.5 on 2019-10-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_auto_20191019_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='state',
        ),
    ]
